### ISSUE TITLE
Delete fails on OpenShift when trying to parse version

### ISSUE THREAD

**Issue by mikz** [kontena/k8s-client#133]
OpenShift returns `1.11.0+d4cacc0` as the gitVersion in the `GET /version` endpoint.
That can't be parsed by `Gem::Version`.

```
I, [2019-06-04T19:00:07.060615 #62646]  INFO -- K8s::Transport<https://master.devel-311.3sca.net:8443>: GET /version => HTTP 200: <K8s::API::Version> in 0.042s
ArgumentError: Malformed version number string 1.11.0+d4cacc0
from /Users/mikz/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/version.rb:208:in `initialize'
 "/Users/mikz/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/version.rb:208:in `initialize'",
 "/Users/mikz/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'",
 "/Users/mikz/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'",
 "/Users/mikz/.gem/ruby/2.4.2/gems/k8s-client-0.10.0/lib/k8s/transport.rb:355:in `need_delete_body?'",
 "/Users/mikz/.gem/ruby/2.4.2/gems/k8s-client-0.10.0/lib/k8s/transport.rb:275:in `request'",
 "/Users/mikz/.gem/ruby/2.4.2/gems/k8s-client-0.10.0/lib/k8s/resource_client.rb:312:in `delete'",
 "/Users/mikz/.gem/ruby/2.4.2/gems/k8s-client-0.10.0/lib/k8s/resource_client.rb:346:in `delete_resource'",
 "/Users/mikz/.gem/ruby/2.4.2/gems/k8s-client-0.10.0/lib/k8s/client.rb:267:in `delete_resource'",
```

**Comment by mikz** [comment]
Wow. That was fast 😍 Good 🥇
