### ISSUE TITLE
excon malformed headers when doing resource update inside of watch

### ISSUE THREAD

**Issue by matti** [kontena/k8s-client#77]
```
  asia_resource.watch() do |asia_watch_event|
    resource = asia_watch_event.resource
    name = resource[:metadata][:name]
    who = resource[:spec][:who]

    resource[:spec][:greeting] = "Hello, #{who}"
    asia_resource.update_resource(resource)
  end
```

will

```
1: from /Users/mpa/.rvm/gems/ruby-2.6.0@operaattori/gems/excon-0.62.0/lib/excon/response.rb:89:in `parse'
/Users/mpa/.rvm/gems/ruby-2.6.0@operaattori/gems/excon-0.62.0/lib/excon/response.rb:186:in `parse_headers': malformed header (Excon::Error::ResponseParse) (Excon::Error::Socket) (Excon::Error::Socket)
```

while

```
  asia_resource.watch() do |asia_watch_event|
    resource = asia_watch_event.resource
    name = resource[:metadata][:name]
    who = resource[:spec][:who]

    resource[:spec][:greeting] = "Hello, #{who}"
    Thread.new do
      asia_resource.update_resource(resource)
    end
  end
```

works

**Comment by kke** [comment]
Anything relevant with `EXCON_DEBUG=true`?

**Comment by matti** [comment]
@kke sent debug output in slack

**Comment by kke** [comment]
The debug info does not contain the piece of header that actually caused the failure :(

```ruby
          key, value = data.split(':', 2)
          raise Excon::Error::ResponseParse, 'malformed header' unless value
```

Would be interesting to know what the `data` looks like, empty values are not allowed in HTTP headers though.

**Comment by kke** [comment]
Though, likely the problem is in the k8s-client and not the server or excon anyway.

**Comment by kke** [comment]
I think it's trying to reuse the SSL socket for the update request while still reading the response for the watch stream.
