### ISSUE TITLE
API discovery needs to deal with HTTP 404/503 errors for apiservice API groups

### ISSUE THREAD

**Issue by SpComb** [kontena/k8s-client#8]
The apiservice API groups (such as the `metrics-server` => `metrics.k8s.io/v1beta1`) seems to to be rather fragile, and the kube apiserver seems to often return HTTP 404 or 503 errors for the `/apis/metrics.k8s.io/v1beta1` endpoint.

I suspect this is related to the `metrics-server` pod backing the api service being broken, so retry wouldn't necessarily help. The client may need some policy to just skip broken API groups for things like stack purge?

**Comment by SpComb** [comment]
Example case, although this is a HTTP 503 for the actual `/apis/metrics.k8s.io/v1beta1/nodes` resources:

```
W, [2018-08-08T13:06:53.733220 #1]  WARN -- K8s::Transport<https://167.99.39.233:6443>: [GET /api/v1/componentstatuses?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/configmaps?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/endpoints?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/events?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/limitranges?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/namespaces?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/nodes?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/persistentvolumeclaims?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/persistentvolumes?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/pods?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/podtemplates?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/replicationcontrollers?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/resourcequotas?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/secrets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/serviceaccounts?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /api/v1/services?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apiregistration.k8s.io/v1/apiservices?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/daemonsets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/deployments?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/ingresses?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/networkpolicies?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/podsecuritypolicies?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/extensions/v1beta1/replicasets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apps/v1/controllerrevisions?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apps/v1/daemonsets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apps/v1/deployments?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apps/v1/replicasets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apps/v1/statefulsets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/events.k8s.io/v1beta1/events?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/autoscaling/v1/horizontalpodautoscalers?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/batch/v1/jobs?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/certificates.k8s.io/v1beta1/certificatesigningrequests?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/networking.k8s.io/v1/networkpolicies?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/policy/v1beta1/poddisruptionbudgets?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/policy/v1beta1/podsecuritypolicies?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/rbac.authorization.k8s.io/v1/clusterroles?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/rbac.authorization.k8s.io/v1/rolebindings?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/rbac.authorization.k8s.io/v1/roles?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/storage.k8s.io/v1/storageclasses?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/scheduling.k8s.io/v1beta1/priorityclasses?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/metrics.k8s.io/v1beta1/nodes?labelSelector=k8s.kontena.io%2Fstack%3Dweave, GET /apis/metrics.k8s.io/v1beta1/pods?labelSelector=k8s.kontena.io%2Fstack%3Dweave] => HTTP 503 Service Unavailable in 0.238s
GET /apis/metrics.k8s.io/v1beta1/nodes => HTTP 503 Service Unavailable
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/transport.rb:171:in `parse_response'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/transport.rb:212:in `block in requests'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/transport.rb:210:in `map'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/transport.rb:210:in `requests'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/transport.rb:242:in `gets'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/resource_client.rb:45:in `list'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/client.rb:96:in `list_resources'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/stack.rb:109:in `prune'
/usr/local/bundle/gems/k8s-client-0.2.1/lib/k8s/stack.rb:96:in `apply'
/app/lib/pharos/phase.rb:97:in `apply_stack'
/app/lib/pharos/phases/configure_weave.rb:41:in `ensure_resources'
/app/lib/pharos/phases/configure_weave.rb:17:in `call'
/app/lib/pharos/phase_manager.rb:70:in `block in apply'
/app/lib/pharos/phase_manager.rb:40:in `block in run_serial'
/app/lib/pharos/phase_manager.rb:39:in `map'
/app/lib/pharos/phase_manager.rb:39:in `run_serial'
/app/lib/pharos/phase_manager.rb:51:in `run'
/app/lib/pharos/phase_manager.rb:67:in `apply'
/app/lib/pharos/cluster_manager.rb:119:in `apply_phase'
/app/lib/pharos/cluster_manager.rb:98:in `apply_phases'
/app/lib/pharos/up_command.rb:104:in `configure'
/app/lib/pharos/up_command.rb:44:in `block in execute'
/app/lib/pharos/up_command.rb:43:in `chdir'
/app/lib/pharos/up_command.rb:43:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:16:in `run'
bin/pharos-cluster:12:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
```

**Comment by SpComb** [comment]
The HTTP 503 errors seem to be triggered by apiserver restarts, once the apiserver and metrics-server settles down the metrics API works again.

This affects `pharos-cluster up` because it hits the metrics API very quickly after running `kubeadm alpha phase controlplane all`, and at that point the metrics apiservice must still be somehow broken... the old kubeclient was probably slow enough to let the apiservice settle down before hitting it?

**Comment by SpComb** [comment]
`EXCON_DEBUG=true` says:

```
excon.response
  :body          => "Error: 'context canceled'\nTrying to reach: 'https://10.250.121.71:443/apis/metrics.k8s.io/v1beta1/nodes?labelSelector=k8s.kontena.io%2Fstack%3Dweave'"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length" => "149"
    "Content-Type"   => "text/plain; charset=utf-8"
    "Date"           => "Thu, 09 Aug 2018 12:51:45 GMT"
  }
  :host          => "167.99.39.233"
  :local_address => "172.17.0.2"
  :local_port    => 54128
  :path          => "/apis/metrics.k8s.io/v1beta1/nodes"
  :port          => 6443
  :reason_phrase => "Service Unavailable"
  :remote_ip     => "167.99.39.233"
  :status        => 503
  :status_line   => "HTTP/1.1 503 Service Unavailable\r\n"
excon.response
  :body          => "{\"kind\":\"PodMetricsList\",\"apiVersion\":\"metrics.k8s.io/v1beta1\",\"metadata\":{\"selfLink\":\"/apis/metrics.k8s.io/v1beta1/pods\"},\"items\":[]}\n"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length" => "135"
    "Content-Type"   => "application/json"
    "Date"           => "Thu, 09 Aug 2018 12:51:45 GMT"
  }
  :host          => "167.99.39.233"
  :local_address => "172.17.0.2"
  :local_port    => 54128
  :path          => "/apis/metrics.k8s.io/v1beta1/pods"
  :port          => 6443
  :reason_phrase => "OK"
  :remote_ip     => "167.99.39.233"
  :status        => 200
  :status_line   => "HTTP/1.1 200 OK\r\n"
```

**Comment by SpComb** [comment]
The 503 errors on the pipelined apiservice resource list requests should be fixed in #11.

**Comment by SpComb** [comment]
The 404 errors on the top-level apigroup `APIResourceList` endpoint seem to be related to kube-apiserver restarts.. the API behaves oddly immediately after a restart:

```
$ curl -kv https://167.99.39.233:6443/apis/metrics.k8s.io/v1beta1
*   Trying 167.99.39.233...
* Connected to 167.99.39.233 (167.99.39.233) port 6443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: kube-apiserver (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=kube-apiserver
* 	 start date: Wed, 08 Aug 2018 11:39:56 GMT
* 	 expire date: Thu, 08 Aug 2019 11:39:57 GMT
* 	 issuer: CN=kubernetes
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /apis/metrics.k8s.io/v1beta1 HTTP/1.1
> Host: 167.99.39.233:6443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Thu, 09 Aug 2018 13:51:14 GMT
< Content-Length: 260
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis/metrics.k8s.io/v1beta1\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
* Connection #0 to host 167.99.39.233 left intact
}
$ curl -kv https://167.99.39.233:6443/apis/metrics.k8s.io/v1beta1
*   Trying 167.99.39.233...
* Connected to 167.99.39.233 (167.99.39.233) port 6443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: kube-apiserver (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=kube-apiserver
* 	 start date: Wed, 08 Aug 2018 11:39:56 GMT
* 	 expire date: Thu, 08 Aug 2019 11:39:57 GMT
* 	 issuer: CN=kubernetes
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /apis/metrics.k8s.io/v1beta1 HTTP/1.1
> Host: 167.99.39.233:6443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 09 Aug 2018 13:51:15 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 167.99.39.233 left intact
$ curl -kv https://167.99.39.233:6443/apis/metrics.k8s.io/v1beta1
*   Trying 167.99.39.233...
* Connected to 167.99.39.233 (167.99.39.233) port 6443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: kube-apiserver (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=kube-apiserver
* 	 start date: Wed, 08 Aug 2018 11:39:56 GMT
* 	 expire date: Thu, 08 Aug 2019 11:39:57 GMT
* 	 issuer: CN=kubernetes
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /apis/metrics.k8s.io/v1beta1 HTTP/1.1
> Host: 167.99.39.233:6443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 461
< Content-Type: application/json
< Date: Thu, 09 Aug 2018 13:51:18 GMT
< 
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nodes",
      "singularName": "",
      "namespaced": false,
      "kind": "NodeMetrics",
      "verbs": [
        "get",
        "list"
      ]
    },
    {
      "name": "pods",
      "singularName": "",
      "namespaced": true,
      "kind": "PodMetrics",
      "verbs": [
        "get",
        "list"
      ]
    }
  ]
* Connection #0 to host 167.99.39.233 left intact
```

**Comment by SpComb** [comment]
Closing this because the HTTP 503 errors are now fixed, and the HTTP 404 errors seem to be related to apiserver restarts. That seems like a bit of a special case, I'm not sure if we want to deal with that here.
