### ISSUE TITLE
Incompatibility issues with active_support

### ISSUE THREAD

**Issue by kke** [kontena/k8s-client#80]
When you have the `deep_merge` and `active_support` both installed, you get:

```
> K8s::Resource.new(...).merge(metadata: { namespace: 'hello' })
ArgumentError: wrong number of arguments (given 2, expected 1)
gems/activesupport-5.2.2/lib/active_support/core_ext/hash/deep_merge.rb:23:in `deep_merge!'
k8s-client-0.6.4/lib/k8s/resource.rb:67:in `merge'
```

Probably dependant on load order, looking at the `deep_merge` sources.

**Comment by jakolehm** [comment]
https://github.com/danielsdeleo/deep_merge#using-deep_merge-in-rails
